### ISSUE TITLE
adicionar o diretório "vendor" no .gitignore

### ISSUE THREAD

**Issue by perna** [fernandogiovanini/multienv-docker#2]
Adicionar o diretório "app/vendor" no .gitignore para agilizar o processo de clone do projeto.

**Comment by fernandogiovanini** [comment]
Eu acho melhor mandar o diretório app/ "vazio" por não fazer parte do projeto.

**Comment by fernandogiovanini** [comment]
Fechei porque é o mesmo assunto da #1
